### PR TITLE
Update the design to match https://qgis.github.io/QGIS-Hugo/

### PR DESCRIPTION
**Pull request by Xpirix**
- This PR is an update for the design to match https://qgis.github.io/QGIS-Hugo/ according to #71 
- A preview has been deployed at https://feed.kartoza.com

## Login page

image

## Home page

image

## Management page

image

## Feed item form

image

## Login page on mobile

image

## Homepage on mobile

image

## Feed form on mobile

image

## Feed list and navigation menu on mobile

image

### CODE REVIEW

**Comment by atsiatserkina** [comment]
hi @Xpirix ! I would suggest checking the styles of header and footer in few days again - on screenshots, I see that Donate button color is lighter than we made recently, and footer is grey but should have another color, see https://qgis.github.io/QGIS-Hugo/
Also I'm not sure if we made a dark small header transparent, I think it should have 100% filling. We will check it too.
Anyway, I really like how it looks with new style and fonts!

**Comment by Xpirix** [comment]
Hi @atsiatserkina and @dqunbp , thanks for the review.
I've updated the main header, second header and footer style/content according to the current https://qgis.github.io/QGIS-Hugo/. You can see these through the screenshots in my first comment (https://github.com/qgis/qgis-feed/pull/72#issue-2144722250).  I can always update them later if there are some new changes on QGIS-Hugo. 

However, I noticed that all the links in the main header are relative and redirect me to pages that don't exist. I'm running the QGIS-Feed local environment on `http://localhost:8000` and when I want to go to the download page from the header, it redirects me to `http://localhost:8000/download` which is not expected. How can I fix this? Is there any parameter I should set in the `qg-top-nav` tag?

**Comment by dqunbp** [comment]
> Hi @atsiatserkina and @dqunbp , thanks for the review. I've updated the main header, second header and footer style/content according to the current https://qgis.github.io/QGIS-Hugo/. You can see these through the screenshots in my first comment ([#72 (comment)](https://github.com/qgis/qgis-feed/pull/72#issue-2144722250)). I can always update them later if there are some new changes on QGIS-Hugo.
> 
> However, I noticed that all the links in the main header are relative and redirect me to pages that don't exist. I'm running the QGIS-Feed local environment on `http://localhost:8000` and when I want to go to the download page from the header, it redirects me to `http://localhost:8000/download` which is not expected. How can I fix this? Is there any parameter I should set in the `qg-top-nav` tag?

There is a `location-prefix` parameter that should be used. In our case, it will be `<qg-top-nav location-prefix="/QGIS-Hugo" ...`. We need to use it because the current QGIS Hugo site has this location, and we should remove it when we go to production.

**Comment by Xpirix** [comment]
Thanks @dqunbp

**Comment by Xpirix** [comment]
@timlinux This change has been deployed

**Pull request merged**
